---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2023-08-19T13:44:06.1115008-04:00"
  name: vote-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deployd/vote
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavoted
  targetNamespace: instavote
